### ISSUE TITLE
ДЗ 8

### ISSUE THREAD

**Issue by AndyAnderyan** [Polyablackwork/Alina-Poliatykina#8]
### **Завдання 3 - 5**
Не бачу обчислень та відповіді.
### **Завдання 8**
Один з варіантів, який допоможе перенести кожне слово на новий рядок
```css
  h1 span {
      width: min-content;
      display: inline-block;
  }
```

### **Завдання 1,2,6,7 - зроблені на 100%**
